# Generated by Django 3.1.1 on 2020-09-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('noteTitle', models.CharField(max_length=100)),
                ('noteContent', models.CharField(max_length=300)),
                ('noteId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
